package com.mojang.minecraft.level;

import com.mojang.minecraft.Entity;
import java.io.Serializable;

/**
 * Represents a grid cell (slot) in the BlockMap's spatial partitioning system.
 * BlockMap$Slot calculates which grid cell a world position belongs to.
 * Slots are used for efficient entity lookup by converting world coordinates to grid indices.
 * Each slot stores the x, y, z grid coordinates (not world coordinates) of a cell.
 * A cell represents a 16x16x16 unit area in world space, indexed into the entity grid.
 *
 * @author Mojang
 */
class BlockMap$Slot implements Serializable {

	/**
	 * Serial version UID for serialization compatibility.
	 */
	public static final long serialVersionUID = 0L;

	/**
	 * The x-coordinate of this slot in the grid (not world space).
	 * Calculated from world x-coordinate divided by 16 and clamped to grid bounds.
	 */
	private int xSlot;

	/**
	 * The y-coordinate of this slot in the grid (not world space).
	 * Calculated from world y-coordinate divided by 16 and clamped to grid bounds.
	 */
	private int ySlot;

	/**
	 * The z-coordinate of this slot in the grid (not world space).
	 * Calculated from world z-coordinate divided by 16 and clamped to grid bounds.
	 */
	private int zSlot;

	/**
	 * Reference to the parent BlockMap that owns this slot.
	 * Used to access grid dimensions and entity grid array.
	 * Synthetic field auto-generated by Java compiler for inner class access.
	 */
	final BlockMap blockMap;


	/**
	 * Constructs a BlockMap$Slot associated with the given BlockMap.
	 * The slot's grid coordinates are uninitialized until init() is called.
	 *
	 * @param parentBlockMap the BlockMap that owns this slot
	 */
	private BlockMap$Slot(BlockMap parentBlockMap) {
		this.blockMap = parentBlockMap;
	}

	/**
	 * Initializes this slot with grid coordinates calculated from world position.
	 * Converts world coordinates (x, y, z) to grid cell indices by dividing by 16.
	 * Clamps grid coordinates to valid range [0, gridWidth), [0, gridDepth), [0, gridHeight).
	 * Negative coordinates are clamped to 0, oversized coordinates clamped to max index.
	 *
	 * @param worldX the world x-coordinate to convert to grid space
	 * @param worldY the world y-coordinate to convert to grid space
	 * @param worldZ the world z-coordinate to convert to grid space
	 * @return this slot for method chaining (fluent interface)
	 */
	public BlockMap$Slot init(float worldX, float worldY, float worldZ) {
		// Convert world coordinates to grid cell indices
		this.xSlot = (int)(worldX / 16.0F);
		this.ySlot = (int)(worldY / 16.0F);
		this.zSlot = (int)(worldZ / 16.0F);

		// Clamp x slot to valid grid range
		if(this.xSlot < 0) {
			this.xSlot = 0;
		}

		// Clamp y slot to valid grid range
		if(this.ySlot < 0) {
			this.ySlot = 0;
		}

		// Clamp z slot to valid grid range
		if(this.zSlot < 0) {
			this.zSlot = 0;
		}

		// Ensure x slot doesn't exceed grid width
		if(this.xSlot >= BlockMap.getWidth(this.blockMap)) {
			this.xSlot = BlockMap.getWidth(this.blockMap) - 1;
		}

		// Ensure y slot doesn't exceed grid depth
		if(this.ySlot >= BlockMap.getDepth(this.blockMap)) {
			this.ySlot = BlockMap.getDepth(this.blockMap) - 1;
		}

		// Ensure z slot doesn't exceed grid height
		if(this.zSlot >= BlockMap.getHeight(this.blockMap)) {
			this.zSlot = BlockMap.getHeight(this.blockMap) - 1;
		}

		return this;
	}

	/**
	 * Adds an entity to the entity list of this grid cell.
	 * Ensures the slot coordinates are valid before adding to prevent out-of-bounds access.
	 * Only adds the entity if all slot coordinates are non-negative.
	 *
	 * @param entity the entity to add to this grid cell
	 */
	public void add(Entity entity) {
		if(this.xSlot >= 0 && this.ySlot >= 0 && this.zSlot >= 0) {
			this.blockMap.entityGrid[(this.zSlot * BlockMap.getDepth(this.blockMap) + this.ySlot) * BlockMap.getWidth(this.blockMap) + this.xSlot].add(entity);
		}

	}

	/**
	 * Removes an entity from the entity list of this grid cell.
	 * Ensures the slot coordinates are valid before removing to prevent out-of-bounds access.
	 * Only removes the entity if all slot coordinates are non-negative.
	 *
	 * @param entity the entity to remove from this grid cell
	 */
	public void remove(Entity entity) {
		if(this.xSlot >= 0 && this.ySlot >= 0 && this.zSlot >= 0) {
			this.blockMap.entityGrid[(this.zSlot * BlockMap.getDepth(this.blockMap) + this.ySlot) * BlockMap.getWidth(this.blockMap) + this.xSlot].remove(entity);
		}

	}

	/**
	 * Synthetic constructor for inner class instantiation via SyntheticClass parameter.
	 * Required by Java compiler for reflective/bytecode access to private constructors.
	 *
	 * @param parentBlockMap the BlockMap that owns this slot
	 * @param syntheticMarker synthetic parameter for compiler identification
	 */
	// $FF: synthetic method
	BlockMap$Slot(BlockMap parentBlockMap, SyntheticClass syntheticMarker) {
		this(parentBlockMap);
	}

	/**
	 * Gets the x-coordinate of this slot in the grid.
	 * Synthetic method for accessing the private xSlot field.
	 *
	 * @param slot the slot to query
	 * @return the grid x-coordinate of the slot
	 */
	// $FF: synthetic method
	static int getXSlot(BlockMap$Slot slot) {
		return slot.xSlot;
	}

	/**
	 * Gets the y-coordinate of this slot in the grid.
	 * Synthetic method for accessing the private ySlot field.
	 *
	 * @param slot the slot to query
	 * @return the grid y-coordinate of the slot
	 */
	// $FF: synthetic method
	static int getYSlot(BlockMap$Slot slot) {
		return slot.ySlot;
	}

	/**
	 * Gets the z-coordinate of this slot in the grid.
	 * Synthetic method for accessing the private zSlot field.
	 *
	 * @param slot the slot to query
	 * @return the grid z-coordinate of the slot
	 */
	// $FF: synthetic method
	static int getZSlot(BlockMap$Slot slot) {
		return slot.zSlot;
	}
}


