package com.mojang.minecraft.level.tile;

/**
 * Represents different sound types that blocks can emit when interacted with.
 * Sound types determine the audio feedback when blocks are stepped on, broken, or placed.
 * Each sound type has a unique volume and pitch multiplier for audio variety.
 * Different materials (grass, stone, wood, metal, cloth, gravel) produce different sounds.
 * The sound type enum enables efficient categorization and audio management for all blocks.
 *
 * @author Mojang
 */
public enum Tile$SoundType {

	/**
	 * Silent sound type - produces no audible feedback.
	 * Used for blocks that should not emit any sound when interacted with.
	 */
	none("none", 0, "-", 0.0F, 0.0F),

	/**
	 * Grass sound type - soft ground impact sound.
	 * Used for grass and soft terrain blocks.
	 * Volume: 0.6F, Pitch multiplier: 1.0F
	 */
	grass("grass", 1, "grass", 0.6F, 1.0F),

	/**
	 * Cloth sound type - soft fabric/wool impact sound.
	 * Used for wool and cloth-like blocks.
	 * Volume: 0.7F, Pitch multiplier: 1.2F
	 */
	cloth("cloth", 2, "grass", 0.7F, 1.2F),

	/**
	 * Gravel sound type - loose stone crunching sound.
	 * Used for gravel and loose aggregate blocks.
	 * Volume: 1.0F, Pitch multiplier: 1.0F
	 */
	gravel("gravel", 3, "gravel", 1.0F, 1.0F),

	/**
	 * Stone sound type - hard impact sound.
	 * Used for stone, cobblestone, and hard mineral blocks.
	 * Volume: 1.0F, Pitch multiplier: 1.0F
	 */
	stone("stone", 4, "stone", 1.0F, 1.0F),

	/**
	 * Metal sound type - resonant metallic impact sound.
	 * Used for metal and ore blocks.
	 * Volume: 1.0F, Pitch multiplier: 2.0F (higher pitch for metallic ring)
	 */
	metal("metal", 5, "stone", 1.0F, 2.0F),

	/**
	 * Wood sound type - hollow wood impact sound.
	 * Used for wood blocks, planks, and wooden structures.
	 * Volume: 1.0F, Pitch multiplier: 1.0F
	 */
	wood("wood", 6, "wood", 1.0F, 1.0F);

	/**
	 * Display name of the sound type.
	 * Used for identification and potential UI display purposes.
	 */
	public final String name;

	/**
	 * Volume multiplier for this sound type.
	 * Determines how loud the sound is when this block is interacted with.
	 * Modified by random variation during actual playback.
	 */
	private final float volumeValue;

	/**
	 * Pitch multiplier for this sound type.
	 * Determines the relative pitch/frequency of the sound.
	 * Higher values produce higher-pitched sounds (e.g., metal rings at 2.0F).
	 */
	private final float pitchValue;

	/**
	 * Array of all sound type enum values.
	 * Synthetic field auto-generated by Java compiler for enum ordinals.
	 */
	// $FF: synthetic field
	private static final Tile$SoundType[] soundTypeArray = new Tile$SoundType[]{none, grass, cloth, gravel, stone, metal, wood};


	/**
	 * Constructs a Tile$SoundType enum constant with sound properties.
	 * Constructor is private as enums are created at class load time.
	 *
	 * @param soundName the name of this sound type (used internally)
	 * @param ordinal the enum ordinal (auto-generated by Java)
	 * @param soundKey the key for looking up the audio file/resource
	 * @param volumeValue the base volume multiplier for this sound type
	 * @param pitchValue the pitch multiplier for this sound type
	 */
	private Tile$SoundType(String soundName, int ordinal, String soundKey, float volumeValue, float pitchValue) {
		this.name = soundKey;
		this.volumeValue = volumeValue;
		this.pitchValue = pitchValue;
	}

	/**
	 * Gets the volume for this sound type with randomization applied.
	 * Applies random variation to volume to prevent audio from sounding too repetitive.
	 * Random variance: 0.4F multiplied by random [0.0, 1.0) plus 1.0F = [1.0, 1.4)
	 * Final volume = baseVolume / randomVariance * 0.5F scaling factor
	 *
	 * @return the calculated volume with random variation applied
	 */
	public final float getVolume() {
		return this.volumeValue / (Block.random.nextFloat() * 0.4F + 1.0F) * 0.5F;
	}

	/**
	 * Gets the pitch for this sound type with randomization applied.
	 * Applies random variation to pitch to prevent audio from sounding too repetitive.
	 * Random variance: 0.2F multiplied by random [0.0, 1.0) plus 0.9F = [0.9, 1.1)
	 * Final pitch = basePitch / randomVariance
	 *
	 * @return the calculated pitch with random variation applied
	 */
	public final float getPitch() {
		return this.pitchValue / (Block.random.nextFloat() * 0.2F + 0.9F);
	}

}


