package com.mojang.minecraft;

/**
 * OperatingSystemLookup is a synthetic utility class generated by the Java compiler.
 * It provides a lookup table that maps operating system enum values to integer identifiers.
 * This class is automatically generated and should not be manually edited.
 *
 * The lookup table enables fast integer-based comparisons for operating system detection.
 * OS Mapping:
 * - Linux: 1
 * - Solaris: 2
 * - Windows: 3
 * - macOS: 4
 */
final class OperatingSystemLookup {

	// Lookup table mapping OS enum ordinals to integer identifiers
	static final int[] lookup = new int[Minecraft$OS.values().length];

	/**
	 * Private constructor to prevent instantiation of this utility class.
	 * This class only contains static initialization and should never be instantiated.
	 */
	private OperatingSystemLookup() {
	}

	// Static initializer that populates the lookup table with OS identifier mappings.
	// Uses try-catch blocks to safely handle potential NoSuchFieldError exceptions
	// that may occur if enum values are renamed or removed.
	static {
		// Initialize Linux OS mapping
		try {
			lookup[Minecraft$OS.linux.ordinal()] = 1;
		} catch (NoSuchFieldError e) {
			// OS value not available - skip initialization for this entry
		}

		// Initialize Solaris OS mapping
		try {
			lookup[Minecraft$OS.solaris.ordinal()] = 2;
		} catch (NoSuchFieldError e) {
			// OS value not available - skip initialization for this entry
		}

		// Initialize Windows OS mapping
		try {
			lookup[Minecraft$OS.windows.ordinal()] = 3;
		} catch (NoSuchFieldError e) {
			// OS value not available - skip initialization for this entry
		}

		// Initialize macOS OS mapping
		try {
			lookup[Minecraft$OS.macos.ordinal()] = 4;
		} catch (NoSuchFieldError e) {
			// OS value not available - skip initialization for this entry
		}
	}
}
